-- 코드를 입력하세요
SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') as PUBLISHED_DATE
FROM BOOK AS B 
JOIN AUTHOR AS A WHERE B.AUTHOR_ID = A.AUTHOR_ID AND CATEGORY LIKE '경제'
# WHERE 
ORDER BY PUBLISHED_DATE ASC